- eap/eap6-amq-persistent-sti.json
- eap/eap6-amq-sti.json
- eap/eap6-basic-sti.json
- eap/eap6-https-sti.json
- eap/eap6-mongodb-persistent-sti.json
- eap/eap6-mongodb-sti.json
- eap/eap6-mysql-persistent-sti.json
- eap/eap6-mysql-sti.json
- eap/eap6-postgresql-persistent-sti.json
- eap/eap6-postgresql-sti.json
[CLOUD-204] Replace DNS_PING with KUBE_PING in Openshift EAP
https://issues.jboss.org/browse/CLOUD-204
> [CLOUD-204] Replace DNS_PING with KUBE_PING in Openshift EAP

- docs/templates/eap/eap6-amq-persistent-sti.adoc
- docs/templates/eap/eap6-amq-sti.adoc
- docs/templates/eap/eap6-basic-sti.adoc
- docs/templates/eap/eap6-https-sti.adoc
- docs/templates/eap/eap6-mongodb-persistent-sti.adoc
- docs/templates/eap/eap6-mongodb-sti.adoc
- docs/templates/eap/eap6-mysql-persistent-sti.adoc
- docs/templates/eap/eap6-mysql-sti.adoc
- docs/templates/eap/eap6-postgresql-persistent-sti.adoc
- docs/templates/eap/eap6-postgresql-sti.adoc
[CLOUD-212] Update docs to reflect change from DNS_PING to KUBE_PING in Openshift EAP
https://issues.jboss.org/browse/CLOUD-212
> [CLOUD-212] Update docs to reflect change from DNS_PING to KUBE_PING in Openshift EAP

- docs/templates/eap/eap6-amq-persistent-sti.adoc
- docs/templates/eap/eap6-amq-sti.adoc
- docs/templates/eap/eap6-basic-sti.adoc
- docs/templates/eap/eap6-https-sti.adoc
- docs/templates/eap/eap6-mongodb-persistent-sti.adoc
- docs/templates/eap/eap6-mongodb-sti.adoc
- docs/templates/eap/eap6-mysql-persistent-sti.adoc
- docs/templates/eap/eap6-mysql-sti.adoc
- docs/templates/eap/eap6-postgresql-persistent-sti.adoc
- docs/templates/eap/eap6-postgresql-sti.adoc
[CLOUD-217] Change openshift PING protocols to only return self if clustering not configured
https://issues.jboss.org/browse/CLOUD-217
> [CLOUD-217] Change openshift PING protocols to only return self if clustering not configured

- amq/amq6-basic.json
- amq/amq6-persistent-ssl.json
- amq/amq6-persistent.json
- amq/amq6-ssl.json
I've made several changes to docs for all four A-MQ templates. Please check the wording since I'm not a native speaker. Don't hesitate to pick only some texts or to modify them before merging.
> Docs for A-MQ templates

- decisionserver/decisionserver6-basic-s2i.json
- decisionserver/decisionserver6-https-s2i.json
- jboss-image-streams.json
[CLOUD-184] Create KIE Server image
https://issues.jboss.org/browse/CLOUD-184
> [CLOUD-184] Create KIE Server image

- decisionserver/decisionserver62-amq-s2i.json
- decisionserver/decisionserver62-basic-s2i.json
- decisionserver/decisionserver62-https-s2i.json
[CLOUD-260] Document decisionserver image
https://issues.jboss.org/browse/CLOUD-260
> [CLOUD-260] Document decisionserver image

- decisionserver/decisionserver62-amq-s2i.json
- decisionserver/decisionserver62-https-s2i.json
- secrets/decisionserver-app-secret.json
[CLOUD-393] decision server should have its own secret and service account
https://issues.jboss.org/browse/CLOUD-393
> [CLOUD-393] decision server should have its own secret and service account

- procexecserver/procexecserver62-mysql-persistent-s2i.json
- procexecserver/procexecserver62-mysql-s2i.json
- procexecserver/procexecserver62-postgresql-s2i.json
CLOUD-470: complete Process Execution Server library quickstart client
https://issues.jboss.org/browse/CLOUD-470
> CLOUD-470: complete Process Execution Server library quickstart client

- jboss-image-streams.json
- processserver/processserver62-mysql-persistent-s2i.json
- processserver/processserver62-mysql-s2i.json
- processserver/processserver62-postgresql-persistent-s2i.json
- processserver/processserver62-postgresql-s2i.json
- secrets/processserver-app-secret.json
CLOUD-476: Rename Process Execution Server to Intelligent Process Server
https://issues.jboss.org/browse/CLOUD-476
> CLOUD-476: Rename Process Execution Server to Intelligent Process Server

- processserver/processserver62-mysql-persistent-s2i.json
- processserver/processserver62-mysql-s2i.json
- processserver/processserver62-postgresql-persistent-s2i.json
- processserver/processserver62-postgresql-s2i.json
CLOUD-482: [processserver] templates contain ping port definition
https://issues.jboss.org/browse/CLOUD-482
> CLOUD-482: [processserver] templates contain ping port definition

- docs/README.adoc
- docs/decisionserver/decisionserver62-amq-s2i.adoc
- docs/decisionserver/decisionserver62-basic-s2i.adoc
- docs/decisionserver/decisionserver62-https-s2i.adoc
- docs/eap/eap64-mongodb-persistent-s2i.adoc
- docs/eap/eap64-mongodb-s2i.adoc
- gen_template_docs.py
Decisionserver docs broke with commit fd648739d4d845baa3dd590936ee23a8cb75cd43; this fixes it and regenerates the docs.
> fix doc generation relating to decisionserver

- processserver/processserver62-amq-mysql-persistent-s2i.json
- processserver/processserver62-amq-mysql-s2i.json
- processserver/processserver62-amq-postgresql-persistent-s2i.json
- processserver/processserver62-amq-postgresql-s2i.json
- processserver/processserver62-basic-s2i.json
- processserver/processserver62-mysql-s2i.json
- processserver/processserver62-postgresql-persistent-s2i.json
- processserver/processserver62-postgresql-s2i.json
CLOUD-493: Add AMQ and basic Intelligent Process Server templates
https://issues.jboss.org/browse/CLOUD-493
> CLOUD-493: Add AMQ and basic Intelligent Process Server templates

- decisionserver/decisionserver62-basic-s2i.json
- decisionserver/decisionserver63-amq-s2i.json
- decisionserver/decisionserver63-basic-s2i.json
- decisionserver/decisionserver63-https-s2i.json
- jboss-image-streams.json
- processserver/processserver63-amq-mysql-persistent-s2i.json
- processserver/processserver63-amq-mysql-s2i.json
- processserver/processserver63-amq-postgresql-persistent-s2i.json
- processserver/processserver63-amq-postgresql-s2i.json
- processserver/processserver63-basic-s2i.json
- processserver/processserver63-mysql-persistent-s2i.json
- processserver/processserver63-mysql-s2i.json
- processserver/processserver63-postgresql-persistent-s2i.json
- processserver/processserver63-postgresql-s2i.json
CLOUD-601: upgrade KIE Server, Decision Server, Process Server from 6.2 to 6.3
https://issues.jboss.org/browse/CLOUD-601
> CLOUD-601: upgrade KIE Server, Decision Server, Process Server from 6.2 to 6.3

- decisionserver/decisionserver62-amq-s2i.json
- decisionserver/decisionserver62-basic-s2i.json
- decisionserver/decisionserver62-https-s2i.json
- decisionserver/decisionserver63-amq-s2i.json
- decisionserver/decisionserver63-basic-s2i.json
- decisionserver/decisionserver63-https-s2i.json
CLOUD-435: [decisionserver] templates contain ping port definition
https://issues.jboss.org/browse/CLOUD-435
> CLOUD-435: [decisionserver] templates contain ping port definition

- eap/eap70-basic-s2i.json
- eap/eap70-https-s2i.json
- eap/eap70-mongodb-persistent-s2i.json
- eap/eap70-mongodb-s2i.json
- eap/eap70-mysql-persistent-s2i.json
- eap/eap70-mysql-s2i.json
- eap/eap70-postgresql-persistent-s2i.json
- eap/eap70-postgresql-s2i.json
- eap/eap70-sso-s2i.json
- sso/sso70-https.json
- sso/sso70-mysql-persistent.json
- sso/sso70-mysql.json
- sso/sso70-postgresql-persistent.json
- sso/sso70-postgresql.json
applies to eap7 and sso7 templates
> CLOUD-515 use jboss-cli.sh to terminate pods running eap7

- decisionserver/decisionserver63-amq-s2i.json
- decisionserver/decisionserver63-basic-s2i.json
- decisionserver/decisionserver63-https-s2i.json
- processserver/processserver63-amq-mysql-persistent-s2i.json
- processserver/processserver63-amq-mysql-s2i.json
- processserver/processserver63-amq-postgresql-persistent-s2i.json
- processserver/processserver63-amq-postgresql-s2i.json
- processserver/processserver63-basic-s2i.json
- processserver/processserver63-mysql-persistent-s2i.json
- processserver/processserver63-mysql-s2i.json
- processserver/processserver63-postgresql-persistent-s2i.json
- processserver/processserver63-postgresql-s2i.json
CLOUD-845: support override for KIE_CONTAINER_DEPLOYMENT
https://issues.jboss.org/browse/CLOUD-845
> CLOUD-845: support override for KIE_CONTAINER_DEPLOYMENT

- decisionserver/decisionserver62-amq-s2i.json
- decisionserver/decisionserver63-amq-s2i.json
- processserver/processserver63-amq-mysql-persistent-s2i.json
- processserver/processserver63-amq-mysql-s2i.json
- processserver/processserver63-amq-postgresql-persistent-s2i.json
- processserver/processserver63-amq-postgresql-s2i.json
CLOUD-584: [IPS] [DecisionServer] AMQ templates queues mismatch
https://issues.jboss.org/browse/CLOUD-584
> CLOUD-584: [IPS] [DecisionServer] AMQ templates queues mismatch

- jboss-image-streams.json
- sso/sso71-https.json
- sso/sso71-mysql-persistent.json
- sso/sso71-mysql.json
- sso/sso71-postgresql-persistent.json
- sso/sso71-postgresql.json
CLOUD-1401: [SSO71] Create new image for Red Hat SSO 7.1
https://issues.jboss.org/browse/CLOUD-1401
Requesting feedback from @wdecoste
> CLOUD-1401: [SSO71] Create new image for Red Hat SSO 7.1

- decisionserver/decisionserver64-amq-s2i.json
- decisionserver/decisionserver64-basic-s2i.json
- decisionserver/decisionserver64-https-s2i.json
- jboss-image-streams.json
- processserver/processserver64-amq-mysql-persistent-s2i.json
- processserver/processserver64-amq-mysql-s2i.json
- processserver/processserver64-amq-postgresql-persistent-s2i.json
- processserver/processserver64-amq-postgresql-s2i.json
- processserver/processserver64-basic-s2i.json
- processserver/processserver64-mysql-persistent-s2i.json
- processserver/processserver64-mysql-s2i.json
- processserver/processserver64-postgresql-persistent-s2i.json
- processserver/processserver64-postgresql-s2i.json
CLOUD-1476: [KIESERVER64] Create images for B*MS v6.4
https://issues.jboss.org/browse/CLOUD-1476
> CLOUD-1476: [KIESERVER64] Create images for B*MS v6.4

- bpmsuite/bpmsuite70-full-mysql.json
- jboss-image-streams.json
- secrets/bpmsuite-app-secret.json
GUVNOR-3028
https://issues.jboss.org/browse/GUVNOR-3028
> GUVNOR-3028

- bpmsuite/bpmsuite70-full-mysql.json
CLOUD-1844: Support External Maven Repos in EAP
https://issues.jboss.org/browse/CLOUD-1844
> CLOUD-1844: Support External Maven Repos in EAP

- bpmsuite/bpmsuite70-full-mysql-persistent.json
@errantepiphany could you please take a quick look?
> [CLOUD-1852] bpmsuite: add business central volume config

- bpmsuite/bpmsuite70-full-mysql-persistent.json
@errantepiphany could you merge this?
CC @sutaakar
> [CLOUD-1852] bpmsuite: add missing ',' (copy&paste error)

- bpmsuite/bpmsuite70-full-mysql-persistent.json
@errantepiphany can you please take a look and merge?
cc @sutaakar
> [CLOUD-1852] bpmsuite: fix BC volume mount path

- sso/sso70-https.json
- sso/sso70-mysql-persistent.json
- sso/sso70-mysql.json
- sso/sso70-postgresql-persistent.json
- sso/sso70-postgresql.json
Signed-off-by: Kyle Liberti <kliberti@redhat.com>
> [CLOUD-1965] [SSO7] Support clean shutdown on TERM

- bpmsuite/bpmsuite70-businesscentral-monitoring-mysql.json
- bpmsuite/bpmsuite70-businesscentral-mysql.json
- bpmsuite/bpmsuite70-executionserver-s2i.json
- bpmsuite/bpmsuite70-executionserver.json
- bpmsuite/bpmsuite70-full-mysql-persistent.json
- jboss-image-streams.json
CLOUD-1845: Support S2I in BPMS 7 KIE Server image
https://issues.jboss.org/browse/CLOUD-1845
> CLOUD-1845: Support S2I in BPMS 7 KIE Server image

- bpmsuite/bpmsuite70-businesscentral-monitoring.json
- bpmsuite/bpmsuite70-executionserver-postgresql.json
[CLOUD-2013] Finalize bpmsuite-7 images for initial Limited Availability release
https://issues.jboss.org/browse/CLOUD-2013
> [CLOUD-2013] Finalize bpmsuite-7 images for initial Limited Availability release

- eap/eap70-basic-s2i.json
- eap/eap70-https-s2i.json
- eap/eap70-mongodb-persistent-s2i.json
- eap/eap70-mongodb-s2i.json
- eap/eap70-mysql-persistent-s2i.json
- eap/eap70-mysql-s2i.json
- eap/eap70-postgresql-persistent-s2i.json
- eap/eap70-postgresql-s2i.json
- eap/eap70-sso-s2i.json
- eap/eap70-third-party-db-s2i.json
- eap/eap71-basic-s2i.json
- eap/eap71-https-s2i.json
- eap/eap71-mongodb-persistent-s2i.json
- eap/eap71-mongodb-s2i.json
- eap/eap71-mysql-persistent-s2i.json
- eap/eap71-mysql-s2i.json
- eap/eap71-postgresql-persistent-s2i.json
- eap/eap71-postgresql-s2i.json
- eap/eap71-sso-s2i.json
- eap/eap71-third-party-db-s2i.json
Signed-off-by: Kyle Liberti <kliberti@redhat.com>
> [CLOUD-1864] [EAP7] Support clean shutdown on TERM

- bpmsuite/bpmsuite70-businesscentral-monitoring-mysql.json
- bpmsuite/bpmsuite70-businesscentral-monitoring.json
- bpmsuite/bpmsuite70-businesscentral-mysql.json
- bpmsuite/bpmsuite70-executionserver-postgresql.json
- bpmsuite/bpmsuite70-executionserver-s2i.json
- bpmsuite/bpmsuite70-executionserver.json
- bpmsuite/bpmsuite70-full-mysql-persistent.json
- bpmsuite/bpmsuite70-full-mysql.json
- jboss-image-streams.json
> move to 1.0.Beta01 for LA

- jboss-image-streams.json
[CLOUD-2006] replace dockerImageRepository with from element
https://issues.jboss.org/browse/CLOUD-2006
> [CLOUD-2006] replace dockerImageRepository with from element

- jboss-image-streams.json
> CLOUD-2062 add back deprecated image streams with hidden tag

- amq/amq63-basic.json
- amq/amq63-persistent-ssl.json
- amq/amq63-persistent.json
- amq/amq63-ssl.json
- decisionserver/decisionserver64-amq-s2i.json
- processserver/processserver64-amq-mysql-persistent-s2i.json
- processserver/processserver64-amq-mysql-s2i.json
- processserver/processserver64-amq-postgresql-persistent-s2i.json
- processserver/processserver64-amq-postgresql-s2i.json
> CLOUD-2063 update references to jboss-amq-63 to use TP tag

- sso/sso70-https.json
- sso/sso70-mysql-persistent.json
- sso/sso70-mysql.json
- sso/sso70-postgresql-persistent.json
- sso/sso70-postgresql.json
- sso/sso71-https.json
- sso/sso71-mysql.json
- sso/sso71-postgresql-persistent.json
- sso/sso71-postgresql.json
Reverts jboss-openshift/application-templates#341
This should have gone into master.
> Revert "CLOUD-1719 add initial delay to liveness probes to avoid premature re…"

- bpmsuite/bpmsuite70-businesscentral-monitoring-with-smartrouter.json
- bpmsuite/bpmsuite70-executionserver-postgresql.json
Updated application templates to use unmanaged execution servers. Updated env variables names.
> CLOUD-1983: Updated templates to unmanaged architecture

- bpmsuite/bpmsuite70-businesscentral-monitoring-with-smartrouter.json
Also removed kie-server user credentials
> CLOUD-2088: External Maven support on BC Monitoring application template

- bpmsuite/bpmsuite70-businesscentral-monitoring-with-smartrouter.json
Reverts jboss-openshift/application-templates#372
> Revert "CLOUD-2088: External Maven support on BC Monitoring application template"

- docs/eap/eap71-amq-persistent-s2i.adoc
- docs/eap/eap71-amq-s2i.adoc
- docs/eap/eap71-basic-s2i.adoc
- docs/eap/eap71-https-s2i.adoc
- docs/eap/eap71-mongodb-persistent-s2i.adoc
- docs/eap/eap71-mongodb-s2i.adoc
- docs/eap/eap71-mysql-persistent-s2i.adoc
- docs/eap/eap71-mysql-s2i.adoc
- docs/eap/eap71-postgresql-persistent-s2i.adoc
- docs/eap/eap71-postgresql-s2i.adoc
- docs/eap/eap71-sso-s2i.adoc
- docs/eap/eap71-third-party-db-s2i.adoc
- eap/eap71-amq-persistent-s2i.json
- eap/eap71-amq-s2i.json
- eap/eap71-basic-s2i.json
- eap/eap71-https-s2i.json
- eap/eap71-mongodb-persistent-s2i.json
- eap/eap71-mongodb-s2i.json
- eap/eap71-mysql-persistent-s2i.json
- eap/eap71-mysql-s2i.json
- eap/eap71-postgresql-persistent-s2i.json
- eap/eap71-postgresql-s2i.json
- eap/eap71-sso-s2i.json
- eap/eap71-third-party-db-s2i.json
- gen_template_docs.py
- jboss-image-streams.json
- Add 1.1 tag to image stream definition
- Modify TP image stream floating tag to point to 1.1
- Update templates to use the TP tag
> Fix EAP 7.1 tags

- jboss-image-streams.json
> remove EAP 7.1 1.1-TP tag

- jboss-image-streams.json
This reverts commit aadf052ca5317c0a833a799d57a0956d1ab82df2.
> Revert "remove EAP 7.1 1.1-TP tag"

- bpmsuite/bpmsuite70-executionserver-externaldb.json
External DB support on application templates
> CLOUD-2087: External DB support on application templates.

- bpmsuite/bpmsuite70-executionserver-postgresql.json
- bpmsuite/bpmsuite70-full-mysql-persistent.json
- bpmsuite/bpmsuite70-full-mysql.json
Depends on https://github.com/jboss-openshift/cct_module/pull/121
@errantepiphany, @rbarriuso or @sutaakar could you please review?
> [CLOUD-2068] add timer store envs to bpmsuite images

- jboss-image-streams.json
- webserver/jws31-tomcat7-basic-s2i.json
- webserver/jws31-tomcat7-https-s2i.json
- webserver/jws31-tomcat7-mongodb-persistent-s2i.json
- webserver/jws31-tomcat7-mongodb-s2i.json
- webserver/jws31-tomcat7-mysql-persistent-s2i.json
- webserver/jws31-tomcat7-mysql-s2i.json
- webserver/jws31-tomcat7-postgresql-persistent-s2i.json
- webserver/jws31-tomcat7-postgresql-s2i.json
- webserver/jws31-tomcat8-basic-s2i.json
- webserver/jws31-tomcat8-https-s2i.json
- webserver/jws31-tomcat8-mongodb-persistent-s2i.json
- webserver/jws31-tomcat8-mongodb-s2i.json
- webserver/jws31-tomcat8-mysql-persistent-s2i.json
- webserver/jws31-tomcat8-mysql-s2i.json
- webserver/jws31-tomcat8-postgresql-persistent-s2i.json
- webserver/jws31-tomcat8-postgresql-s2i.json
These [new iconClass](https://github.com/openshift/origin-web-console/pull/2313) are coming in OpenShift 3.7 
@rcernich PTAL
Signed-off-by: sspeiche <sspeiche@redhat.com>
> Update image-stream to include new iconClass 

- webserver/jws31-tomcat7-mongodb-persistent-s2i.json
> Fix typo in jws31-tomcat7-modified-persistent-s2i display name

- eap/eap71-tx-recovery-s2i.json
> CLOUD-2210: transaction recovery template for EAP 7.1

- eap/eap64-tx-recovery-s2i.json
- eap/eap70-tx-recovery-s2i.json
- eap/eap71-tx-recovery-s2i.json
> mark tx-recovery templates as tech-preview

- amq/amq63-basic.json
- amq/amq63-ssl.json
Duplicate of https://github.com/jboss-openshift/application-templates/pull/449#pullrequestreview-114795539, but submitted from a branch.
Signed-off-by: Vanessa Busch <vbusch@redhat.com>
> [CLOUD-2505] Remove hidden tag from templates for openshift online.

- eap/eap71-image-stream.json
https://issues.jboss.org/browse/CLOUD-2594
> remove EAP 7.1 TP imagestream entries

- decisionserver/decisionserver64-amq-s2i.json
- decisionserver/decisionserver64-basic-s2i.json
- decisionserver/decisionserver64-https-s2i.json
- docs/decisionserver/decisionserver64-amq-s2i.adoc
- docs/decisionserver/decisionserver64-basic-s2i.adoc
- docs/decisionserver/decisionserver64-https-s2i.adoc
- docs/processserver/processserver64-amq-mysql-persistent-s2i.adoc
- docs/processserver/processserver64-amq-mysql-s2i.adoc
- docs/processserver/processserver64-amq-postgresql-persistent-s2i.adoc
- docs/processserver/processserver64-amq-postgresql-s2i.adoc
- docs/processserver/processserver64-basic-s2i.adoc
- docs/processserver/processserver64-mysql-persistent-s2i.adoc
- docs/processserver/processserver64-mysql-s2i.adoc
- docs/processserver/processserver64-postgresql-persistent-s2i.adoc
- docs/processserver/processserver64-postgresql-s2i.adoc
- processserver/processserver64-amq-mysql-persistent-s2i.json
- processserver/processserver64-amq-mysql-s2i.json
- processserver/processserver64-amq-postgresql-persistent-s2i.json
- processserver/processserver64-amq-postgresql-s2i.json
- processserver/processserver64-basic-s2i.json
- processserver/processserver64-mysql-persistent-s2i.json
- processserver/processserver64-mysql-s2i.json
- processserver/processserver64-postgresql-persistent-s2i.json
- processserver/processserver64-postgresql-s2i.json
Signed-off-by: Ant Stephenson <anstephe@redhat.com>
> CLOUD-2579 Fix version for quickstarts version mismatch.

- amq/amq63-basic.json
- amq/amq63-image-stream.json
- amq/amq63-persistent-ssl.json
- amq/amq63-persistent.json
- amq/amq63-ssl.json
Signed-off-by: Howard Gao <howard.gao@gmail.com>
> Updating amq63 to latest 1.4

- datavirt/datavirt63-basic-s2i.json
- datavirt/datavirt63-extensions-support-s2i.json
- datavirt/datavirt63-secure-s2i.json
[CLOUD-2701] Updated JDV 6.3 templates with hidden tag
> [CLOUD-2701] Updated JDV 6.3 templates with hidden tag

- eap/eap71-amq-persistent-s2i.json
- eap/eap71-amq-s2i.json
- eap/eap71-mongodb-persistent-s2i.json
- eap/eap71-mongodb-s2i.json
- eap/eap71-mysql-persistent-s2i.json
- eap/eap71-mysql-s2i.json
- eap/eap71-postgresql-persistent-s2i.json
- eap/eap71-postgresql-s2i.json
- eap/eap71-third-party-db-s2i.json
- eap/eap71-tx-recovery-s2i.json
https://issues.jboss.org/browse/CLOUD-2766
Signed-off-by: Ken Wills <kwills@redhat.com>
> CLOUD-2766 - correct some EAP 7.1 tx-recovery-s2i template parameters

- processserver/processserver63-image-stream.json
- processserver/processserver64-image-stream.json
> CLOUD-2751 update processserver image streams to registry.redhat.io

- amq/amq62-image-stream.json
Signed-off-by: Howard Gao <howard.gao@gmail.com>
> restore amq62-image-stream.json

- eap/eap64-tx-recovery-postgresql-s2i.json
https://issues.jboss.org/browse/CLOUD-2542
template for jdbc txn recovery for eap6.4 too
/CC @luck3y
> [CLOUD-2542] eap64 txn recovery template storing data to postgresql

- eap/eap64-amq-persistent-s2i.json
- eap/eap64-amq-s2i.json
- eap/eap64-basic-s2i.json
- eap/eap64-https-s2i.json
- eap/eap64-image-stream.json
- eap/eap64-mongodb-persistent-s2i.json
- eap/eap64-mongodb-s2i.json
- eap/eap64-mysql-persistent-s2i.json
- eap/eap64-mysql-s2i.json
- eap/eap64-postgresql-persistent-s2i.json
- eap/eap64-postgresql-s2i.json
- eap/eap64-sso-s2i.json
- eap/eap64-third-party-db-s2i.json
- eap/eap64-tx-recovery-postgresql-s2i.json
- eap/eap64-tx-recovery-s2i.json
- eap/eap70-image-stream.json
- eap/eap71-amq-persistent-s2i.json
- eap/eap71-amq-s2i.json
- eap/eap71-basic-s2i.json
- eap/eap71-https-s2i.json
- eap/eap71-image-stream.json
- eap/eap71-mongodb-persistent-s2i.json
- eap/eap71-mongodb-s2i.json
- eap/eap71-mysql-persistent-s2i.json
- eap/eap71-mysql-s2i.json
- eap/eap71-postgresql-persistent-s2i.json
- eap/eap71-postgresql-s2i.json
- eap/eap71-sso-s2i.json
- eap/eap71-third-party-db-s2i.json
- eap/eap71-tx-recovery-s2i.json
https://issues.jboss.org/browse/CLOUD-3088
https://issues.jboss.org/browse/CLOUD-3089
Signed-off-by: Ken Wills <kwills@redhat.com>
> CLOUD-3089 / CLOUD-3088 - update imagestreams and templates for EAP 6.4 / 7.1
