jboss-openshift/application-templates

eap/eap6-mongodb-sti.json, webserver/jws-tomcat7-mongodb-sti.json, webserver/jws-tomcat8-mongodb-sti.json
Ever since https://github.com/openshift/mongodb/pull/31 was merged, the mongo image
requires that you specify the admin password.
@kconner
=> Add now mandatory MONGODB_ADMIN_PASSWORD

amq/amq6.json, eap/eap6-amq-sti.json, eap/eap6-mongodb-sti.json, eap/eap6-mysql-sti.json, eap/eap6-postgresql-sti.json, webserver/jws-tomcat7-mongodb-sti.json, webserver/jws-tomcat7-mysql-sti.json, webserver/jws-tomcat7-postgresql-sti.json, webserver/jws-tomcat8-mongodb-sti.json, webserver/jws-tomcat8-mysql-sti.json, webserver/jws-tomcat8-postgresql-sti.json
Using '[a-zA-Z0-9]{8}' expressions can occasionally generate
usernames beginning with a digit, which is often forbidden.
=> Add a 'user' prefix for usernames in templates

decisionserver/decisionserver62-amq-s2i.json, decisionserver/decisionserver62-basic-s2i.json, decisionserver/decisionserver62-https-s2i.json
[CLOUD-357] Ensure decisionserver templates work with no parameters being specified
https://issues.jboss.org/browse/CLOUD-357
=> [CLOUD-357] Ensure decisionserver templates work with no parameters being specified

datagrid/datagrid65-https.json, datagrid/datagrid65-mysql-persistent.json, datagrid/datagrid65-mysql.json, datagrid/datagrid65-postgresql-persistent.json, datagrid/datagrid65-postgresql.json, eap/eap64-amq-persistent-s2i.json, eap/eap64-amq-s2i.json, eap/eap64-https-s2i.json, eap/eap64-mongodb-persistent-s2i.json, eap/eap64-mongodb-s2i.json, eap/eap64-mysql-persistent-s2i.json, eap/eap64-mysql-s2i.json, eap/eap64-postgresql-persistent-s2i.json, eap/eap64-postgresql-s2i.json
I've added env variable JDG_JGROUPS_ENCRYPT_KEYSTORE_DIR to all templates that already use secret for HTTPS and also added mount for that directory. This variable is used further in infinispan-config.sh.
See https://gitlab.mw.lab.eng.bos.redhat.com/cloudenablement/jboss-dockerfiles/merge_requests/409 for reference.
=> [CLOUD-337] JGroups keystore directory in a variable

decisionserver/decisionserver63-amq-s2i.json, decisionserver/decisionserver63-basic-s2i.json, decisionserver/decisionserver63-https-s2i.json, processserver/processserver63-amq-mysql-persistent-s2i.json, processserver/processserver63-amq-mysql-s2i.json, processserver/processserver63-amq-postgresql-persistent-s2i.json, processserver/processserver63-amq-postgresql-s2i.json, processserver/processserver63-basic-s2i.json, processserver/processserver63-mysql-persistent-s2i.json, processserver/processserver63-mysql-s2i.json, processserver/processserver63-postgresql-persistent-s2i.json, processserver/processserver63-postgresql-s2i.json
CLOUD-641: Add multi-version Container support to KIE Server
https://issues.jboss.org/browse/CLOUD-641
=> CLOUD-641: Add multi-version Container support to KIE Server

decisionserver/decisionserver62-amq-s2i.json, decisionserver/decisionserver63-amq-s2i.json, processserver/processserver63-amq-mysql-persistent-s2i.json, processserver/processserver63-amq-mysql-s2i.json, processserver/processserver63-amq-postgresql-persistent-s2i.json, processserver/processserver63-amq-postgresql-s2i.json, processserver/processserver63-mysql-persistent-s2i.json, processserver/processserver63-mysql-s2i.json, processserver/processserver63-postgresql-persistent-s2i.json, processserver/processserver63-postgresql-s2i.json
https://issues.jboss.org/browse/CLOUD-584
[IPS] [DecisionServer] AMQ templates queues mismatch
https://issues.jboss.org/browse/CLOUD-589
CLOUD-589: [kie-server] Ability to specify KIE.SERVER.REQUEST queue
https://issues.jboss.org/browse/CLOUD-590
[kie-server] executor consumer ignores KIE_SERVER_EXECUTOR_JMS_QUEUE
https://issues.jboss.org/browse/CLOUD-605
[kie-server] "Disabling JMS support in executor" with non-AMQ templates
=> CLOUD-584, CLOUD-589, CLOUD-590, CLOUD-605

decisionserver/decisionserver63-amq-s2i.json, decisionserver/decisionserver63-basic-s2i.json, decisionserver/decisionserver63-https-s2i.json, processserver/processserver63-amq-mysql-persistent-s2i.json, processserver/processserver63-amq-mysql-s2i.json, processserver/processserver63-amq-postgresql-persistent-s2i.json, processserver/processserver63-amq-postgresql-s2i.json, processserver/processserver63-basic-s2i.json, processserver/processserver63-mysql-persistent-s2i.json, processserver/processserver63-mysql-s2i.json, processserver/processserver63-postgresql-persistent-s2i.json, processserver/processserver63-postgresql-s2i.json
CLOUD-673: [IPS] Allow workflow for using multiple container versions with KIE_CONTAINER_REDIRCT_ENABLED in the default template
https://issues.jboss.org/browse/CLOUD-673
=> CLOUD-673: [IPS] Allow workflow for using multiple container versions with KIE_CONTAINER_REDIRCT_ENABLED in the default template

eap/eap70-sso-s2i.json, jboss-image-streams.json
Also removed "Tech Preview" from sso image stream description.
=> CLOUD-813 add missing SERVICE_ACCOUNT_NAME parameter to eap70-sso-s2i

processserver/processserver63-amq-mysql-persistent-s2i.json, processserver/processserver63-amq-postgresql-persistent-s2i.json
CLOUD-730: added missing AMQ_SPLIT template parameter
https://issues.jboss.org/browse/CLOUD-730
Added missing template parameter to:
processserver/processserver63-amq-mysql-persistent-s2i.json
processserver/processserver63-amq-postgresql-persistent-s2i.json
=> CLOUD-730: added missing AMQ_SPLIT template parameter

eap/eap64-amq-persistent-s2i.json, eap/eap64-amq-s2i.json, eap/eap64-basic-s2i.json, eap/eap64-https-s2i.json, eap/eap64-mongodb-persistent-s2i.json, eap/eap64-mongodb-s2i.json, eap/eap64-mysql-persistent-s2i.json, eap/eap64-mysql-s2i.json, eap/eap64-postgresql-persistent-s2i.json, eap/eap64-postgresql-s2i.json, eap/eap64-third-party-db-s2i.json, eap/eap70-amq-persistent-s2i.json, eap/eap70-amq-s2i.json, eap/eap70-basic-s2i.json, eap/eap70-https-s2i.json, eap/eap70-mongodb-persistent-s2i.json, eap/eap70-mongodb-s2i.json, eap/eap70-mysql-persistent-s2i.json, eap/eap70-mysql-s2i.json, eap/eap70-postgresql-persistent-s2i.json, eap/eap70-postgresql-s2i.json, eap/eap70-third-party-db-s2i.json
The SSO templates already exposes this parameter, no need to change them.
=> [CLOUD-449] Expose ARTIFACT_DIR as parameter in s2i templates (EAP)

jboss-image-streams.json
…s to all image stream tag definitions
Some files have multiple image Stream Tag definitions, I added the openshift/display-name var to the image stream tag definitions which refer to the application being built from the template. For example, for templates like eap64-amq-persistent-s2i.json, I added the openshift/display-name vars to the image stream tag definitions which were named ${APPLICATION_NAME}:latest but not to the ones named "jboss-eap64-openshift:1.4" or "jboss-amq-62:1.3". Is this the right way to do this? 
*NOTE: My script cleaned up some typos and indentation(a couple of the datavirt files had duplicate env lists). I can put this in a seperate commit/PR if you think that is better.
=> [CLOUD-1382] [CLOUD-1383] Add openshift.io/display-name to all image stream tag definitions

bpmsuite/bpmsuite70-businesscentral-monitoring-ephemeral.json, bpmsuite/bpmsuite70-executionserver-postgresql-persistent.json, bpmsuite/bpmsuite70-full-mysql-persistent.json, bpmsuite/bpmsuite70-full-mysql.json
Initial implementation of BPMS templates for OpenShift, including:
* Ephemeral Business Central Monitoring + Smart router
* Execution server + PostgreSQL DB
Remarks:
* Execution server and BC controller credentials (user/pass) are hardcoded so they match on both templates.
* The only HTTP is supported.
* No need to create "bpmsuite-service-account"
=> CLOUD-1983: Initial implementation of BPMS templates

bpmsuite/bpmsuite70-businesscentral-monitoring-with-smartrouter.json
There is no need to set this variable as it is required for Smart router internal purposes. It is used to tell smart router what IP address it should listen on for HTTP requests.
@psiroky @errantepiphany What do you think about it?
=> Set Smart router host IP from pod IP

secrets/datavirt-app-secret.yaml
Issue: [CLOUD-1867](https://issues.jboss.org/browse/CLOUD-1867)
Changes default value for APP_DATADIR (== data). Also, change tests to rely on new default value for APP_DATADIR.
Update datavirt-app-config secret to use new src location (/opt/eap/standalone/data/).
Add a new CTF test for custom APP_DATADIR value.
This PR works in conjunction with [#74](https://github.com/jboss-openshift/cct_module/pull/74) in cct_module.
This PR replaces [#305](https://github.com/jboss-openshift/application-templates/pull/305) in application-templates.
Please make sure your PR meets following requirements:
=> [CLOUD-1867] update datavirt-app-config secret to use new src location

jboss-image-streams.json, sso.adoc.in, sso/README.md, sso/sso72-https.json, sso/sso72-mysql-persistent.json, sso/sso72-mysql.json, sso/sso72-postgresql-persistent.json, sso/sso72-postgresql.json
* [CLOUD-2237] Add definition of ```sso72-*``` image stream and application templates
Basic proposed templates sanity testing was performed on local OCP v3.7 instance. All five of the proposed templates seem to be working fine (the underlying RH-SSO 7.2 server instance in pod is running, and able to login as RH-SSO admin via the RH-SSO administrator console).     
* [KEYCLOAK-6399] sso/README.md updates:
- Replace listing of deprecated sso70-* templates with listing of the current ```sso71-*``` and ```sso72-*``` ones
- Restructure the format of the ```sso/README.md``` file
* [CLOUD-1782] ```sso.adoc.in``` ```sso/README.md``` Replace the deprecated hardcoded RH-SSO server admin username/password credentials with the currently recommended use of ```SSO_ADMIN_USERNAME``` and …
=> [CLOUD-2237] [KEYCLOAK-6399] [CLOUD-1782] Define sso72- image stream and application templates. Also do couple of sso/README.md text updates

eap/eap71-amq-persistent-s2i.json, eap/eap71-amq-s2i.json, eap/eap71-basic-s2i.json, eap/eap71-https-s2i.json, eap/eap71-image-stream.json, eap/eap71-mongodb-persistent-s2i.json, eap/eap71-mongodb-s2i.json, eap/eap71-mysql-persistent-s2i.json, eap/eap71-mysql-s2i.json, eap/eap71-postgresql-persistent-s2i.json, eap/eap71-postgresql-s2i.json, eap/eap71-sso-s2i.json, eap/eap71-third-party-db-s2i.json, eap/eap71-tx-recovery-s2i.json
This is needed to fetch the parent pom used in the EAP 7.1.0.GA quickstarts.
https://issues.jboss.org/browse/CLOUD-2365
https://issues.jboss.org/browse/CLOUD-2206
=> CLOUD-2365 - allow MAVEN_ARGS_APPEND to work for S2I builds

sso/README.md, sso/sso72-https.json, sso/sso72-mysql-persistent.json, sso/sso72-mysql.json, sso/sso72-postgresql-persistent.json, sso/sso72-postgresql.json, sso/sso72-x509-https.json, sso/sso72-x509-mysql-persistent.json, sso/sso72-x509-postgresql-persistent.json
```
Renamed:    sso72-mysql-persistent.json -> sso72-passthrough-mysql-persistent.json
Renamed:    sso72-mysql.json -> sso72-passthrough-mysql.json
Renamed:    sso72-postgresql-persistent.json -> sso72-passthrough-postgresql-persistent.json
Renamed:    sso72-postgresql.json -> sso72-passthrough-postgresql.json
Renamed:    sso72-https.json -> sso72-passthrough.json
```
Also:
* Replace 'SSO' with 'RH-SSO' where appropriate,
* Add 'displayName' field to MEMORY_LIMIT variable
Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>
Note: This is a replacement for original CLOUD-2367 one. Instead of removing the `HTTP_HOSTNAME` / `HTTPS_HOSTNAME` variables, the agreement was to:
* Keep the `HTTP_HOSTNAME` / HTTPS_HOSTNAME` variables,
* Rename the templates using `passthrough` TLS termination mode …
=> [CLOUD-2367] Rename existing templates using passthrough TLS termination mode

eap/eap64-image-stream.json, eap/eap71-image-stream.json
https://issues.jboss.org/browse/CLOUD-2401
This adds a :latest IS tag that points to the :latest docker image
=> CLOUD-2401 [EAP7] Align image import instructions and image name / version tags

eap/eap71-tx-recovery-s2i.json
https://issues.jboss.org/browse/CLOUD-2261
Adding new system role with permission to query api to get list of pods. This is needed for case the recovery of transaction is done via apy querying as discussed at CLOUD-2261 and at document https://docs.google.com/document/d/1JdOTMP6pdexJ__KYlw9hgwR6DOCHTtYCQy7PqyMk8OU/edit
/cc @rcernich
=> [CLOUD-2261] adding permisssion to list pods

eap/eap64-tx-recovery-s2i.json
https://issues.jboss.org/browse/CLOUD-2261
There is a missing `View` role for the tx-recovery template for eap 6.4 which is needed for the fix of CLOUD-2261.
The follow-up to the PR: https://github.com/jboss-openshift/application-templates/pull/447
/cc @rcernich
=> [CLOUD-2261] adding permisssion to list pods for eap txn recovery template for EAP64

sso/README.md, sso/sso72-x509-https.json, sso/sso72-x509-mysql-persistent.json, sso/sso72-x509-postgresql-persistent.json
Drop the:
- JGroups secret auto-generation, and
- associated JGroups volume and volumeMount
from x509 templates. These are not needed, since JGroups auto-generates its own private/public key pair.
Update README.md
Enable JGroups ASYM_ENCRYPT for RH-SSO x509 templates by default.
Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>
=> [CLOUD-2437] Templates changes related with JGroups ASYM_ENCRYPT support
